/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "observer.h"

bool_t
xdr_stamp (XDR *xdrs, stamp *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->proccess_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->action_number))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_wakeup_response (XDR *xdrs, wakeup_response *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->process_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_wakeup_reponse (XDR *xdrs, wakeup_reponse *objp)
{
	register int32_t *buf;

	 if (!xdr_wakeup_response (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sndmsg_response (XDR *xdrs, sndmsg_response *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->process, MAX_PROCESSES,
		sizeof (stamp), (xdrproc_t) xdr_stamp))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->stamp_number))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_action_report (XDR *xdrs, action_report *objp)
{
	register int32_t *buf;

	 if (!xdr_stamp (xdrs, &objp->process_stamp))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->action_type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->process_target))
		 return FALSE;
	return TRUE;
}
